import Foundation

public enum KeyCodes {

    public static func modifierNames(_ bits: UInt8) -> [String] {
        var result: [String] = []
        if bits & 0x02 != 0 { result.append("Shift") }
        if bits & 0x04 != 0 { result.append("Ctrl") }
        if bits & 0x08 != 0 { result.append("Alt") }
        if bits & 0x10 != 0 { result.append("Win") }
        return result
    }

    public static func usageName(_ usage: UInt8) -> String {
        switch usage {
        case 0x00: return "None"
        case 0x04: return "A"
        case 0x05: return "B"
        case 0x06: return "C"
        case 0x07: return "D"
        case 0x08: return "E"
        case 0x09: return "F"
        case 0x0A: return "G"
        case 0x0B: return "H"
        case 0x0C: return "I"
        case 0x0D: return "J"
        case 0x0E: return "K"
        case 0x0F: return "L"
        case 0x10: return "M"
        case 0x11: return "N"
        case 0x12: return "O"
        case 0x13: return "P"
        case 0x14: return "Q"
        case 0x15: return "R"
        case 0x16: return "S"
        case 0x17: return "T"
        case 0x18: return "U"
        case 0x19: return "V"
        case 0x1A: return "W"
        case 0x1B: return "X"
        case 0x1C: return "Y"
        case 0x1D: return "Z"
        case 0x1E: return "1"
        case 0x1F: return "2"
        case 0x20: return "3"
        case 0x21: return "4"
        case 0x22: return "5"
        case 0x23: return "6"
        case 0x24: return "7"
        case 0x25: return "8"
        case 0x26: return "9"
        case 0x27: return "0"
        case 0x28: return "Enter"
        case 0x29: return "Esc"
        case 0x2A: return "Backspace"
        case 0x2B: return "Tab"
        case 0x2C: return "Space"
        case 0x2D: return "Minus"
        case 0x2E: return "="
        case 0x2F: return "["
        case 0x30: return "]"
        case 0x31: return "\\"
        case 0x33: return ";"
        case 0x34: return "'"
        case 0x35: return "`"
        case 0x36: return ","
        case 0x37: return "."
        case 0x38: return "/"
        case 0x39: return "CapsLock"
        case 0x3A: return "F1"
        case 0x3B: return "F2"
        case 0x3C: return "F3"
        case 0x3D: return "F4"
        case 0x3E: return "F5"
        case 0x3F: return "F6"
        case 0x40: return "F7"
        case 0x41: return "F8"
        case 0x42: return "F9"
        case 0x43: return "F10"
        case 0x44: return "F11"
        case 0x45: return "F12"
        case 0x46: return "PrintScreen"
        case 0x47: return "ScrollLock"
        case 0x48: return "Pause"
        case 0x49: return "Insert"
        case 0x4A: return "Home"
        case 0x4B: return "PageUp"
        case 0x4C: return "Delete"
        case 0x4D: return "End"
        case 0x4E: return "PageDown"
        case 0x4F: return "→"
        case 0x50: return "←"
        case 0x51: return "↓"
        case 0x52: return "↑"
        case 0x53: return "NumLock"
        case 0x54: return "Num/"
        case 0x55: return "Num*"
        case 0x56: return "Num-"
        case 0x57: return "Num+"
        case 0x58: return "NumEnter"
        case 0x59: return "Num1"
        case 0x5A: return "Num2"
        case 0x5B: return "Num3"
        case 0x5C: return "Num4"
        case 0x5D: return "Num5"
        case 0x5E: return "Num6"
        case 0x5F: return "Num7"
        case 0x60: return "Num8"
        case 0x61: return "Num9"
        case 0x62: return "Num0"
        case 0x63: return "Num."
        case 0x65: return "AppMenu"
        case 0xE0: return "Ctrl"
        case 0xE1: return "Shift"
        case 0xE2: return "Alt"
        case 0xE3: return "Win"
        default: return String(format: "0x%02X", usage)
        }
    }

    public static func mediaName(_ usage: UInt16) -> String? {
        switch usage {
        case 0xE9: return "Volume Up"
        case 0xEA: return "Volume Down"
        case 0xE2: return "Mute"
        case 0xB5: return "Next Track"
        case 0xB6: return "Previous Track"
        case 0xB7: return "Stop"
        case 0xCD: return "Play/Pause"
        case 0x81: return "Launch"
        case 0x82: return "Back"
        case 0x83: return "Search"
        case 0x84: return "Home"
        case 0x85: return "Calculator"
        case 0x86: return "My Computer"
        case 0x94: return "Reset"
        case 0xB0: return "Play"
        case 0xB1: return "Pause"
        case 0xB2: return "Record"
        case 0xB3: return "Rewind"
        case 0xB4: return "Fast Forward"
        case 0x96: return "Messages"
        case 0x97: return "Mail"
        default: return nil
        }
    }
}
